CONNECT RESET;

CREATE DATABASE Userio;
CONNECT TO Userio;
GRANT DBADM, SECADM ON DATABASE TO DB2ADMIN;
CREATE SCHEMA DB2ADMIN AUTHORIZATION DB2ADMIN;
CONNECT RESET;
CONNECT TO Userio user DB2ADMIN using db2admin;

CREATE TABLE Userio (
    nombre VARCHAR(32) NOT NULL PRIMARY KEY,
    password VARCHAR(32) NOT NULL,
    lectura BOOLEAN NOT NULL,
    escritura BOOLEAN NOT NULL,
    admin BOOLEAN NOT NULL
);

CREATE TABLE Userio_Eliminado (
    nombre VARCHAR(32) NOT NULL PRIMARY KEY,
    password VARCHAR(32) NOT NULL,
    lectura BOOLEAN NOT NULL,
    escritura BOOLEAN NOT NULL,
    admin BOOLEAN NOT NULL,

    usuario_eliminador VARCHAR(32),
    fecha_eliminacion DATE NOT NULL
) PARTITION BY RANGE(fecha_eliminacion)(
    STARTING '1/1/2000' ENDING '1/1/2030' EVERY 2 MONTHS
);